// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB53oI4KlkfGNpT8dYTP7CKhi0YwCRMaYc',
    appId: '1:435556032700:web:b2dd73e3d6e5ed9971f0b9',
    messagingSenderId: '435556032700',
    projectId: 'cutalkproj',
    authDomain: 'cutalkproj.firebaseapp.com',
    storageBucket: 'cutalkproj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYpYN7BSJt6_hB-uSoZ6xMkpAANKcpVzI',
    appId: '1:435556032700:android:356276928a0d117571f0b9',
    messagingSenderId: '435556032700',
    projectId: 'cutalkproj',
    storageBucket: 'cutalkproj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB78RTtWUx5DsgKNwpBUpXSojTeubWwNhI',
    appId: '1:435556032700:ios:4f3c340f7f53513771f0b9',
    messagingSenderId: '435556032700',
    projectId: 'cutalkproj',
    storageBucket: 'cutalkproj.appspot.com',
    iosClientId: '435556032700-kkauqbubaq7doivojc64krt27r696f4j.apps.googleusercontent.com',
    iosBundleId: 'com.korayliman.cutalk',
  );
}
